### ISSUE TITLE
Request for Ability to Scan Classes For Annotations

### ISSUE THREAD

**Issue by iarepandemonium** [KnockturnMC/KnockturnCommons#4]
I would like to make a request that the module loader would provide us a method to scan classes for annotations, so I can do something cool with the class if it has the annotation I want, and possibly get the data from the annotation.

**Comment by lynxplay** [comment]
Providing a custom class visitor to the AnnotationModuleDescriptor should suffice for that task:

https://github.com/KnockturnMC/KnockturnCommons/blob/master/src/main/java/com/knockturnmc/api/ext/loader/descriptors/ModuleAnnotationDescriptor.java#L30
